CREATE DATABASE IF NOT EXISTS survey_db;
USE survey_db;

CREATE TABLE IF NOT EXISTS area2_responses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    q1 TINYINT NOT NULL,
    q2 TINYINT NOT NULL,
    q3 TINYINT NOT NULL,
    q4 TINYINT NOT NULL,
    q5 TINYINT NOT NULL,
    q6 TINYINT NOT NULL,
    q7 TINYINT NOT NULL,
    q8 TINYINT NOT NULL,
    q9 TINYINT NOT NULL,
    q10 TINYINT NOT NULL,
    q11 TINYINT NOT NULL,
    q12 TINYINT NOT NULL,
    submitted_at DATETIME NOT NULL
);
