CREATE TABLE IF NOT EXISTS area5_responses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    q1 TINYINT,
    q2 TINYINT,
    q3 TINYINT,
    q4 TINYINT,
    q5 TINYINT,
    q6 TINYINT,
    q7 TINYINT,
    q8 TINYINT,
    q9 TINYINT,
    q10 TINYINT,
    q11 TINYINT,
    q12 TINYINT,
    q13 TINYINT,
    q14 TINYINT,
    q15 TINYINT,
    submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP
);