CREATE DATABASE IF NOT EXISTS survey_db;
USE survey_db;

-- Area 6: External Relations
CREATE TABLE IF NOT EXISTS area6_responses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    q1 TINYINT NOT NULL,
    q2 TINYINT NOT NULL,
    q3 TINYINT NOT NULL,
    q4 TINYINT NOT NULL,
    q5 TINYINT NOT NULL,
    q6 TINYINT NOT NULL,
    q7 TINYINT NOT NULL,
    q8 TINYINT NOT NULL,
    q9 TINYINT NOT NULL,
    q10 TINYINT NOT NULL,
    q11 TINYINT NOT NULL,
    q12 TINYINT NOT NULL,
    q13 TINYINT NOT NULL,
    q14 TINYINT NOT NULL,
    q15 TINYINT NOT NULL,
    q16 TINYINT NOT NULL,
    q17 TINYINT NOT NULL,
    q18 TINYINT NOT NULL,
    q19 TINYINT NOT NULL,
    q20 TINYINT NOT NULL,
    q21 TINYINT NOT NULL,
    q22 TINYINT NOT NULL,
    submitted_at DATETIME NOT NULL
);

-- Area 7: Research
CREATE TABLE IF NOT EXISTS area7_responses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    q1 TINYINT NOT NULL,
    q2 TINYINT NOT NULL,
    q3 TINYINT NOT NULL,
    q4 TINYINT NOT NULL,
    q5 TINYINT NOT NULL,
    q6 TINYINT NOT NULL,
    q7 TINYINT NOT NULL,
    q8 TINYINT NOT NULL,
    q9 TINYINT NOT NULL,
    q10 TINYINT NOT NULL,
    q11 TINYINT NOT NULL,
    q12 TINYINT NOT NULL,
    q13 TINYINT NOT NULL,
    submitted_at DATETIME NOT NULL
);

-- Area 8: Results
CREATE TABLE IF NOT EXISTS area8_responses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    q1 TINYINT NOT NULL,
    q2 TINYINT NOT NULL,
    q3 TINYINT NOT NULL,
    q4 TINYINT NOT NULL,
    q5 TINYINT NOT NULL,
    q6 TINYINT NOT NULL,
    q7 TINYINT NOT NULL,
    q8 TINYINT NOT NULL,
    q9 TINYINT NOT NULL,
    q10 TINYINT NOT NULL,
    q11 TINYINT NOT NULL,
    q12 TINYINT NOT NULL,
    q13 TINYINT NOT NULL,
    q14 TINYINT NOT NULL,
    q15 TINYINT NOT NULL,
    q16 TINYINT NOT NULL,
    q17 TINYINT NOT NULL,
    q18 TINYINT NOT NULL,
    q19 TINYINT NOT NULL,
    q20 TINYINT NOT NULL,
    q21 TINYINT NOT NULL,
    q22 TINYINT NOT NULL,
    q23 TINYINT NOT NULL,
    submitted_at DATETIME NOT NULL
);